return {
  -- {
  --   'nvim-treesitter/nvim-treesitter',
  --   branch = "main",
  --   lazy = false,
  --   build = ":TSUpdate",
  --   config = function()
  --     require("nvim-treesitter").setup({
  --       auto_install = true,
  --     })
  --     vim.api.nvim_create_autocmd('FileType', {
  --       pattern = {
  --         "help",
  --         "bash",
  --         "c",
  --         "cpp",
  --         "css",
  --         "dockerfile",
  --         "erb",
  --         "fish",
  --         "go",
  --         "html",
  --         "htmldjango",
  --         "javascript",
  --         "json",
  --         "lua",
  --         "make",
  --         "python",
  --         "ruby",
  --         "rust",
  --         "shell",
  --         "sql",
  --         "surql",
  --         "svg",
  --         "toml",
  --         "typescript",
  --         "xml",
  --         "yaml",
  --       },
  --       callback = function() vim.treesitter.start() end,
  --     })
  --   end,
  --   -- dependencies = {
  --   --   'RRethy/nvim-treesitter-endwise',
  --   --   'nvim-treesitter/nvim-treesitter-textobjects',
  --   -- },
  -- }, {
  --   'DariusCorvus/tree-sitter-surrealdb.nvim',
  --   dependencies = { 'nvim-treesitter/nvim-treesitter'},
  --   ft = { 'rust', 'surql' },
  --   config = function()
  --     require('tree-sitter-surrealdb').setup()
  --   end,
  -- }
}
